# Generated by Django 4.2 on 2023-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='النص الأصلي')),
                ('repeated_text', models.TextField(blank=True, null=True, verbose_name='النص المعدل (يتم توليده تلقائياً)')),
            ],
            options={
                'verbose_name': 'حذف مكرر',
                'verbose_name_plural': 'حذف المكرر',
            },
        ),
    ]
