# Generated by Django 4.2 on 2023-04-25 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0003_department_websiteactivity_websitefield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrasah.websiteactivity', verbose_name='نشاط المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrasah.websitefield', verbose_name='مجال المشروع'),
        ),
    ]
