# Generated by Django 4.2 on 2023-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0004_alter_project_website_activity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterModelOptions(
            name='websiteactivity',
            options={'verbose_name': 'نشاط موقع', 'verbose_name_plural': 'نشاط موقع'},
        ),
        migrations.AlterModelOptions(
            name='websitefield',
            options={'verbose_name': 'مجال موقع', 'verbose_name_plural': 'مجال موقع'},
        ),
        migrations.AlterField(
            model_name='websitefield',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المجال'),
        ),
    ]
