# Generated by Django 4.2 on 2023-04-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0005_delete_department_alter_websiteactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رابط الحقل'),
        ),
    ]
