# Generated by Django 4.2 on 2023-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0006_alter_field_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='الموعد النهائي المتوقع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بداية المشروع'),
        ),
    ]
