# Generated by Django 4.2 on 2023-04-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0007_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrasah.database', verbose_name='قاعدة البيانات'),
        ),
        migrations.AlterField(
            model_name='field',
            name='page',
            field=models.ForeignKey(blank=True, limit_choices_to={'project__in': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrasah.project')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrasah.page', verbose_name='الصفحة'),
        ),
    ]
