# Generated by Django 4.2 on 2023-04-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0008_alter_field_database_alter_field_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fahrasah.page', verbose_name='الصفحة'),
        ),
    ]
