# Generated by Django 4.2 on 2023-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrasah', '0009_alter_field_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='property',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='خصائص الحقل'),
        ),
    ]
